apiVersion: v1
data:
  config.json: |
    {
        "api": {
            "port": {{ .Values.api.port }}
        },
        "monitor": {
            "port": {{ .Values.monitor.port }}
        },
        "log" : {
            "name": "pacs_store_service",
            "level": "{{ .Values.log.level }}"
        },
        "pacs": {
            "host": "{{ .Values.pacs.host }}",
            "port": {{ .Values.pacs.port }},
            "aet" : "{{ .Values.pacs.aet }}",
            "aec": "{{ .Values.pacs.aec }}"
        },
        "rabbit": {
            "host": "{{ .Values.rabbit.host }}",
            "port": {{ .Values.rabbit.port }},
            "queue": "{{ .Values.rabbit.queue }}",
            "CONNECTION_BACKOFF_ATTEMPTS": {{ .Values.rabbit.attempts }},
            "SLEEP_BETWEEN_ATTEMPTS": {{ .Values.rabbit.sleep }}

        }
    }
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
