{{ if .Values.persistence.enabled }}        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "psschart.fullname" . }}-claim
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}